### ISSUE TITLE
Content now showing in resource detail page

### ISSUE THREAD

**Issue by Moussa112** [NikolaySav/nova-json-schema-field#3]
Hello friend

I am using this package to let users fill in an array in a user friendly way. This array is stored as a string (json object) in the database. Everything works great however in de detail page of resource the field is not displayed.

This is my detail page:

<img width="502" alt="Screenshot 2019-08-06 at 09 10 09" src="https://user-images.githubusercontent.com/6680307/62518565-288d5900-b82a-11e9-9dda-c041d8689d06.png">

This is my edit page:

<img width="979" alt="Screenshot 2019-08-06 at 09 10 45" src="https://user-images.githubusercontent.com/6680307/62518576-30e59400-b82a-11e9-8d7e-a724db9e02fe.png">

It is stored correctly in the database but something goes wrong when trying to display it in the detail page.

**Comment by jedrzej** [comment]
@Moussa112 were you able to work around this issue?

**Comment by rsubr** [comment]
@jedrzej detail page display issue can be fixed by removing the `slot` VueJS tags from [DetailField.vue](https://github.com/NikolaySav/nova-json-schema-field/blob/master/resources/js/components/DetailField.vue).

I created an improved version of this Nova Field.

https://github.com/rsubr/nova-json-schema-field

The calling API is a little different, it supports HTML text, numbers, dates and select fields.
